### ISSUE TITLE
RFE: provide a list of files an RPM installs + their size

### ISSUE THREAD

**Issue by TomasTomecek** [minimization/content-resolver#11]
I really love the listing where the UI tells me the size of a binary RPM: would it make sense to break this down even further and list all the files an RPM install + size of the files?

**Comment by asamalik** [comment]
Thanks for the suggestion!

I'm curious how would you use it?

Have you heard about `rpminspect`? It basically does this for packages, on their every build. Maybe Feedback Pipeline coul link to those results? Or do you see a benefit of Feedback 
Pipeline having this data in itself?

Cheers!

**Comment by TomasTomecek** [comment]
Yup, linking sounds good!

I just wish to have a convenient way to have access to those data. Because I can do it easily in CLI - but that's switching my context since I'm browsing the interface of the feedback pipeline.

**Comment by asamalik** [comment]
Speaking of linking, you just gave me an interesting idea: packages could have a link to bugzilla if there is an open bug related to minimization!

**Comment by yselkowitz** [comment]
Is there still a use for this?

**Comment by TomasTomecek** [comment]
Not from my side, feel free to close.
