### ISSUE TITLE
RFE: a way to deal with alternatives

### ISSUE THREAD

**Issue by erig0** [minimization/content-resolver#17]
There doesn't appear to be any way to select an "alternative" in a workload. e.g. `iptables` could be `iptables-nft` or `iptables-legacy`. How do I select an alternative?

```
[root@vmhost-fedora-test1 ~]# alternatives --list
[..]
iptables                auto    /usr/sbin/iptables-legacy
ebtables                auto    /usr/sbin/ebtables-legacy
arptables               auto    /usr/sbin/arptables-nft
```

**Comment by marceloleitner** [comment]
Cc'ing @asamalik 
If the default priorities are not enough and need to be different from those in Fedora, it can be adjusted by adding a %if 0{?rhel}  condition in Fedora's spec file (while CentOS Stream doesn't get branched out of it).

[root@localhost ~]# alternatives --display iptables
iptables - status is auto.
 link currently points to /usr/sbin/iptables-legacy
/usr/sbin/iptables-legacy - **priority 10**
 slave ip6tables: /usr/sbin/ip6tables-legacy
 slave ip6tables-restore: /usr/sbin/ip6tables-legacy-restore
 slave ip6tables-save: /usr/sbin/ip6tables-legacy-save
 slave iptables-restore: /usr/sbin/iptables-legacy-restore
 slave iptables-save: /usr/sbin/iptables-legacy-save
/usr/sbin/iptables-nft - **priority 5**
 slave ip6tables: /usr/sbin/ip6tables-nft
 slave ip6tables-restore: /usr/sbin/ip6tables-nft-restore
 slave ip6tables-save: /usr/sbin/ip6tables-nft-save
 slave iptables-restore: /usr/sbin/iptables-nft-restore
 slave iptables-save: /usr/sbin/iptables-nft-save
Current `best' version is /usr/sbin/iptables-legacy.

Does this handle it?

**Comment by yselkowitz** [comment]
The way we've been handling this in ELN is to add `Suggests:` to fedora-release-eln that lists the desired implementation of each virtual provide, and (where needed) to block other implementations in Content Resolver.  Workloads themselves should also not use ambiguous names.
