### ISSUE TITLE
Please add support for defining workloads using groups

### ISSUE THREAD

**Issue by adelton** [minimization/content-resolver#18]
Hello,

we'd like to keep an eye on @core and @core dependencies. Looking at https://github.com/minimization/content-resolver/blob/master/config_specs/workload.yaml, defining workloads using groups is not supported.

Please add support for defining workloads using groups, not just packages.

Thank you.

**Comment by adelton** [comment]
Hello @asamalik, any estimate if this feature would be possible to implement, and in which timeframe? Thank you.

**Comment by asamalik** [comment]
Working on it!

Sorry for the delay, I've had quite a lot going on. But this should not be hard to add.

**Comment by asamalik** [comment]
Done!

You can now use

```
  groups:
  - core
```

... in your workloads.

**Comment by adelton** [comment]
Thank you, we will give it a try.
