### ISSUE TITLE
RFE: A way to remove a list of packages after a workload is installed

### ISSUE THREAD

**Issue by ansasaki** [minimization/content-resolver#22]
I am interested in the following use-case: after the packages of a workload are installed, remove a list of packages which I don't want to be present. Such packages could be brought as dependencies.

This list could be provided as part of the workload configuration.

**Comment by asamalik** [comment]
Do you have a specific example?

My thinking is: if something gets pulled into a workload as a dependency, it needs to be there. So you can't just remove it, it's a dependency of something.

**Comment by ansasaki** [comment]
> Do you have a specific example?
> 
> My thinking is: if something gets pulled into a workload as a dependency, it needs to be there. So you can't just remove it, it's a dependency of something.

There is the case when a group is added to a workload but we want some of the packages to not be present in the end. If we include the option "include-weak-deps" to include the weak dependencies, then the number of packages not necessarily required increases even more.
