### ISSUE TITLE
Add the ability to specify accounting for weak dependencies on a per workload basis

### ISSUE THREAD

**Issue by Conan-Kudo** [minimization/content-resolver#31]
Some workloads (like KDE Plasma Desktop) have numerous weak dependencies that lead to a fully functional experience. These weak dependencies are declared as weak dependencies as a compromise, not because the intended desktop experience is to go without them.

It would be great if this intention can be codified in the workloads being tracked by the content resolver, so that we can have weak dependencies included (obviously denoted specially in the graph and charts) so that we can be sure we've captured everything.

**Comment by asamalik** [comment]
You can do that today! See the `include-weak-deps` option in the [workload config spec](https://github.com/minimization/content-resolver/blob/master/config_specs/workload.yaml#L67).

**Comment by asamalik** [comment]
Just please note it'll enable that for every single package. There isn't (or wasn't the last time I checked) an option to DNF to do this selectively.
