### ISSUE TITLE
Implement CI for this repo - initial setup

### ISSUE THREAD

**Issue by asamalik** [minimization/content-resolver#32]
My goal is to make Content Resolver easier to contribute by others. And because it's a fairly complex thing, people need to have confidence that their changes didn't break something. Especially now when one of the things I want this project to focus on is performance improvements (which will involve concurency and other fun stuff).

So let's set up a CI and a set of tests for the core functionality, to make sure our changes don't break Content Resolver.

The initial setup (this issue) is about:

* Setting up a CI for this repo using GitHub Actions (needs to run in a Fedora container)
* A basic test that just runs Content Resolver with the test configs on every PR

**Comment by regexowl** [comment]
I'm happy to take it!

**Comment by asamalik** [comment]
Perfect! If you need any help, please let me know :)

**Comment by asamalik** [comment]
@regexowl Thank you so much for your contribution.
