### ISSUE TITLE
Packages missing in content resolver despite being in ELN

### ISSUE THREAD

**Issue by hhorak** [minimization/content-resolver#48]
See python3-toml being in the ELN repo:
https://odcs.fedoraproject.org/composes/production/latest-Fedora-ELN/compose/AppStream/x86_64/os/Packages/python3-toml-0.10.2-11.eln125.noarch.rpm

but the app does not think it exist in eln:
https://tiny.distro.builders/view-rpm--view-eln--python3-toml.html

**Comment by hroncok** [comment]
> If a package isn't in Content Resolver that would mean it wasn't included in a workload, nor pulled in as a dependency.

Which would make its presence in ELN a bug?

python-wheel-wheel is listed in https://github.com/minimization/content-resolver-input/blob/main/configs/sst_cs_apps-python-crb.yaml

**Comment by asamalik** [comment]
> > If a package isn't in Content Resolver that would mean it wasn't included in a workload, nor pulled in as a dependency.
> 
> Which would make its presence in ELN a bug?

Yeah, not sure how often are packages cleaned up. I don't believe it's manual, but can't tell how often it happens. @sgallagher you probably know

> 
> python-wheel-wheel is listed in https://github.com/minimization/content-resolver-input/blob/main/configs/sst_cs_apps-python-crb.yaml

The repo config definitely isn't automated, so someone would need to put it in CRB. At least it's being built for ELN and included in the overall set.

**Comment by hroncok** [comment]
> vice-versa as @hroncok pointed out -- https://tiny.distro.builders/view-rpm--view-eln--python-wheel-wheel.html page says python-wheel-wheel exists, but I don't see it in the ELN repository.

This one is now in https://odcs.fedoraproject.org/composes/production/latest-Fedora-ELN/compose/CRB/x86_64/os/Packages/ which is correct.

**Comment by sgallagher** [comment]
These packages are appearing in the ELN _compose_ but that's not actually the same thing as being "in ELN". They're showing up there because they're being pulled in by content in ELN-Extras, which is the precursor to EPEL 10.

Their presence in the compose is definitely confusing and I'm going to use https://github.com/fedora-eln/eln/issues/156 to track separating ELN-Extras content out more properly.

**Comment by asamalik** [comment]
Here's the ELN Extras view in Content Resolver: https://tiny.distro.builders/view-packages--view-eln-extras.html

**Comment by yselkowitz** [comment]
Closing this out by noting that Content Resolver does not entirely control the content of ELN; pungi configs and comps also play a factor.  Having Content Resolver somehow affect/generate/replace those has been discussed as a concept, but in the meantime, the answer to such questions is going to be to update pungi configs and/or comps.
