### ISSUE TITLE
Why is python3-babel in AppStream

### ISSUE THREAD

**Issue by hroncok** [minimization/content-resolver#58]
Hello, could you please help me understand why is this package in AppStream?

https://tiny.distro.builders/view-rpm--view-eln--python3-babel.html

It is runtime-required by 3 packages - 2 are in buildroot and one is in CRB.

We maintain this package as a CRB-only dependency of Sphinx (also CRB-only). We do not wish to maintain it in AppStream, but we do not know who should own it there. Based on the visible data, this should also be in CRB-only.

Thanks.

**Comment by asamalik** [comment]
Not answering, just providing context: Content Resolver doesn't compute the repos, it just shows where the pacakges are right now. And that's set in a Pungi config (likely the `prepopulate.json`) somewhere. (So whoever set it will need to answer your question, but it's not computed in CR.)

**Comment by hroncok** [comment]
Do you know where is the Pugni config located?

**Comment by hroncok** [comment]
git blame led me to this commit by @sgallagher https://pagure.io/pungi-fedora/c/53060b422df26a86daa4f06d9bbef151236ce3d8?branch=eln

But that commit is rather large and does not mention where the file originated.

**Comment by hroncok** [comment]
an earlier commit also by @sgallagher https://pagure.io/pungi-fedora/c/56e81cc15434337e11378bd78b697537fb64fbca?branch=eln

This commit mentions CentOS Stream.

On c9s, python3-babel is pulled into AppStream by python3-jinja2. However, that runtime dependency no longer exists in the current ELN version of python3-jinja2.

Should I open a PR that changes prepopulate.json?

**Comment by sgallagher** [comment]
Yes, please submit an MR to fix prepopulate.json. We're trying to find a less unwieldy way to manage the repo split, but this is the best we have at the moment.

**Comment by hroncok** [comment]
https://pagure.io/pungi-fedora/pull-request/1211
